apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cl7rw600u-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cl7rw600u-go 
  name: cl7rw600u-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cl7rw600u-go 
